### ISSUE TITLE
Unsupported Major Minor version error with jdk1.6

### ISSUE THREAD

**Issue by skaluva** [tools4j/unix4j#41]
Hi,
Currently i have jdk1.6 version installed.
java version "1.6.0_04"
Java(TM) SE Runtime Environment (build 1.6.0_04-b12)
Java HotSpot(TM) Server VM (build 10.0-b19, mixed mode)

I'm unable to use this library with the above java version. I'm getting below error:  Could you please check.

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/unix4j/unix/wc/WcOptions : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
        at java.security.AccessController.doPrivileged(Native Method)
```

**Comment by terzerm** [comment]
Please use jdk1.7.

**Comment by skaluva** [comment]
Thanks for the response. It would be good if you mention the same i.e, supported java versions in your wiki page. :)
