### ISSUE TITLE
Command cut is not working

### ISSUE THREAD

**Issue by otros-systems** [tools4j/unix4j#42]
Running following code:
`Unix4j.fromString("some string").cut("-c4-8").toStringResult();`

Throws exception:
```
java.lang.IllegalArgumentException: cannot convert --options value '[c, 4, -, 8]' into the type org.unix4j.unix.cut.CutOptions for cut command

	at org.unix4j.unix.cut.CutArguments.convert(CutArguments.java:131)
	at org.unix4j.unix.cut.CutArguments.convertList(CutArguments.java:105)
	at org.unix4j.unix.cut.CutArguments.getForContext(CutArguments.java:183)
	at org.unix4j.unix.cut.CutArguments.getForContext(CutArguments.java:21)
	at org.unix4j.command.AbstractCommand.getArguments(AbstractCommand.java:40)
	at org.unix4j.unix.cut.CutCommand.execute(CutCommand.java:22)
	at org.unix4j.command.JoinedCommand.execute(JoinedCommand.java:101)
	at org.unix4j.builder.DefaultCommandBuilder.toOutput(DefaultCommandBuilder.java:134)
	at org.unix4j.builder.DefaultCommandBuilder.toStringResult(DefaultCommandBuilder.java:165)

```

I'm using version 0.3

**Comment by terzerm** [comment]
Your format is wrong. You have two options for your example:
```java
Unix4j.fromString("some string").cut(Cut.Options.c, 4, 5, 6, 7, 8).toStringResult();
Unix4j.fromString("some string").cut(Cut.Options.c, Range.between(4, 8)).toStringResult();
```
Please check check javadoc for exact usage of commands, e.g. for cut [here](http://www.unix4j.org/javadoc/org/unix4j/unix/Cut.html) and also the full interface specification [here](http://www.unix4j.org/javadoc/org/unix4j/unix/Cut.Interface.html).

Note also that you _can_ invoke the command with strings, but range was unfortunately not supported. I have pushed a fix (available in 0.4-SNAPSHOT, i.e. if you build Unix4j from sources). With those newest changes you can also do
```java
Unix4j.fromString("some string").cut("-c", "4,5,6,7,8").toStringResult();
Unix4j.fromString("some string").cut("-c", "4-8").toStringResult();
```
For more examples, see cut related tests in (ExampleTest.java)(https://github.com/tools4j/unix4j/blob/master/unix4j-examples/src/test/java/org/unix4j/example/ExampleTest.java)
