### ISSUE TITLE
Cannot use on AIX

### ISSUE THREAD

**Issue by bommo1** [tools4j/unix4j#75]
```
java.lang.IllegalStateException: Cannot evaluate OS constant for current operating system: AIX
	at org.unix4j.util.OS.current(OS.java:46) ~[unix4j-base-0.6.jar!/:na]
	at org.unix4j.util.FileUtil.isWindows(FileUtil.java:28) ~[unix4j-base-0.6.jar!/:na]
	at org.unix4j.util.FileUtil.<clinit>(FileUtil.java:25) ~[unix4j-base-0.6.jar!/:na]
	at org.unix4j.io.FileInput.getFileInfo(FileInput.java:147) ~[unix4j-base-0.6.jar!/:na]
```

As I see in the code only Windows is treated differently.
Please add AIX (and maybe OTHER) in the enum.

Thank you!

**Comment by terzerm** [comment]
Thanks for reporting this and for the pull request.  Looks good at quick glance --- will check in more. detail e.g. what impact Other has.
Will keep you posted.

**Comment by terzerm** [comment]
Fixed in a slightly different way, but thanks for reporting and for the pull request.
